services:
  postgres:
    image: postgres:16-alpine
    profiles: ["server"]
    container_name: nlp_postgres
    environment:
      POSTGRES_DB: second_brain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_case  # Replace with actual password
    volumes:
      - postgres_data:/var/lib/postgresql/data # where the persistent data is stored
      - ./nlp_pipeline/sql/:/docker-entrypoint-initdb.d # the init script that is run only once, reset w/ docker down -v
    ports:
      - "5432:5432"
    networks:
      - nlp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-embedder:
    mem_limit: 10g
    build: 
      context: ./nlp_pipeline
      dockerfile: Dockerfile.embedder   # copy, paste, rename of original Docker file
    profiles: ["worker"]
    command: celery -A celery_worker worker --queues=embed_tasks --concurrency=4 --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    # depends_on:
    #   - redis
    #   - postgres
    # optional: restart if it crashes
    restart: unless-stopped
    # networks:
    #   - nlp_network
    stdin_open: true
    tty: true
    #runtime : nvidia # comment out this line for systems w/o gpu + drivers/software to access via docker

  celery-doc-parser:
    mem_limit: 10g
    build: 
      context: ./nlp_pipeline
      dockerfile: Dockerfile   # original docker file, pared down for just this task
    profiles: ["worker"]
    command: celery -A celery_doc_parser worker --queues=parse_docs --concurrency=2 --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
    # depends_on:
    #   - redis
    #   - postgres
    # optional: restart if it crashes
    restart: unless-stopped
    # networks:
    #   - nlp_network
    stdin_open: true
    tty: true

  # The original nlp python worker file. This has the main loop that listens for messages from the flask ui
  # and dispatches to celery or calls a blocking stored procedure ( both of which are pretty fast )
  nlp_pipeline:
    mem_limit: 10g
    memswap_limit: 10g
    build: 
      context: ./nlp_pipeline
      dockerfile: Dockerfile.pipeline
    profiles: ["worker"]
    command: python worker.py
    container_name: nlp_python
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: second_brain
      DB_USER: postgres
      DB_PASSWORD: test_case
      REDIS_URL: redis://redis:6379

    volumes:
      - ./data:/app/data

    # networks:
    #   - nlp_network
    stdin_open: true
    tty: true
    
  redis:
      image: redis:alpine    
      profiles: ["server"]
      networks: 
        - nlp_network  
  
  flask_app:
    build: ./flask_app # path to the directory containing the Dockerfile
    profiles: ["server"]
    ports:
      - "0.0.0.0:8000:5000"
    networks:
      - nlp_network
    volumes:
      - ./flask_app:/app

volumes:
  postgres_data:

networks:
  nlp_network:
    driver: bridge  
