services:
  postgres:
    image: postgres:16-alpine
    container_name: nlp_postgres
    environment:
      POSTGRES_DB: second_brain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_case  # Replace with actual password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./nlp_pipeline/sql/:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - nlp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery-embedder:
    mem_limit: 10g
    build: 
      context: ./nlp_pipeline
      dockerfile: Dockerfile   # same Dockerfile as your existing python worker
    command: celery -A celery_worker worker --queues=embed_tasks --concurrency=4 --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - postgres
    # optional: restart if it crashes
    restart: unless-stopped
    networks:
      - nlp_network
    stdin_open: true
    tty: true

  celery-doc-parser:
    mem_limit: 10g
    build: 
      context: ./nlp_pipeline
      dockerfile: Dockerfile   # same Dockerfile as your existing python worker
    command: celery -A celery_doc_parser worker --queues=parse_docs --concurrency=4 --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
      - postgres
    # optional: restart if it crashes
    restart: unless-stopped
    networks:
      - nlp_network
    stdin_open: true
    tty: true

  nlp_pipeline:
    mem_limit: 10g
    memswap_limit: 10g
    build: 
      context: ./nlp_pipeline
      dockerfile: Dockerfile
    container_name: nlp_python
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: second_brain
      DB_USER: postgres
      DB_PASSWORD: test_case
      REDIS_URL: redis://redis:6379
      NVIDIA_VISIBLE_DEVICES : all
      NVIDIA_DRIVER_CAPABILITIES : compute,utility

    volumes:
      - ./data:/app/data

    networks:
      - nlp_network
    stdin_open: true
    tty: true
    runtime : nvidia
    

  redis:
      image: redis:alpine    
      networks: 
        - nlp_network  
  
  flask_app:
    build: ./flask_app # path to the directory containing the Dockerfile
    ports:
      - "0.0.0.0:8000:5000"
    networks:
      - nlp_network

volumes:
  postgres_data:

networks:
  nlp_network:
    driver: bridge  
